class Autogenerated {
  bool? success;
  int? code;
  String? message;
  String? title;
  List<Res>? res;

  Autogenerated({this.success, this.code, this.message, this.title, this.res});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    code = json['code'];
    message = json['message'];
    title = json['title'];
    if (json['res'] != null) {
      res = <Res>[];
      json['res'].forEach((v) {
        res!.add(new Res.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['success'] = this.success;
    data['code'] = this.code;
    data['message'] = this.message;
    data['title'] = this.title;
    if (this.res != null) {
      data['res'] = this.res!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Res {
  int? id;
  String? image;
  String? backgroundColor;
  String? style;
  String? sectionId;

  Res({this.id, this.image, this.backgroundColor, this.style, this.sectionId});

  Res.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    image = json['image'];
    backgroundColor = json['background_color'];
    style = json['style'];
    sectionId = json['section_id'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['image'] = this.image;
    data['background_color'] = this.backgroundColor;
    data['style'] = this.style;
    data['section_id'] = this.sectionId;
    return data;
  }
}
